export const INVALID_CREDENTIALS_ERROR_ID = 'M-IC001';
export const EMAIL_ALREADY_REGISTERED_ERROR_ID = 'M-EAR002';
export const USER_NOT_AUTHORIZED_ERROR_ID = 'M-UNA003';
export const EMAIL_NOT_EXIST_ERROR_ID = 'M-ENE004';
export const PASSWORD_RESET_FAILED_ERROR_ID = 'M-PRF005';
export const INVALID_RESET_TOKEN_ERROR_ID = 'M-IRT006';
export const ACCOUNT_LOCKED_ERROR_ID = 'M-AL007';
